# Generated by Django 5.1.4 on 2025-11-07 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=200)),
                ('type_of_work', models.CharField(max_length=300)),
                ('site', models.CharField(max_length=300)),
                ('start_from', models.DateField()),
                ('end_at', models.DateField()),
                ('value', models.BigIntegerField()),
            ],
        ),
    ]
