# Generated by Django 5.1.4 on 2025-11-08 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strengthmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=400)),
                ('quantity', models.IntegerField(null=True)),
            ],
        ),
    ]
