# Generated by Django 5.1.4 on 2025-11-23 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0002_strengthmodel'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='workmodel',
            new_name='Workmodels',
        ),
        migrations.DeleteModel(
            name='Strengthmodel',
        ),
    ]
