# Generated by Django 5.1.4 on 2025-11-23 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0003_rename_workmodel_workmodels_delete_strengthmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Strengthmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
