# Generated by Django 5.1.4 on 2025-11-23 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0004_strengthmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipmentmodel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('quantity', models.IntegerField()),
            ],
        ),
    ]
