# Generated by Django 5.2.8 on 2025-12-09 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0005_equipmentmodel'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='equipmentmodel',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='equipmentmodel',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
