# Generated by Django 5.2.8 on 2025-12-09 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0006_alter_equipmentmodel_options_equipmentmodel_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='strengthmodel',
            options={'ordering': ['order']},
        ),
        migrations.AlterModelOptions(
            name='workmodels',
            options={'ordering': ['order']},
        ),
        migrations.AddField(
            model_name='strengthmodel',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='workmodels',
            name='order',
            field=models.IntegerField(default=0),
        ),
    ]
