# Generated by Django 5.2.8 on 2025-12-10 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0007_alter_strengthmodel_options_alter_workmodels_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodels',
            name='end_at',
            field=models.IntegerField(help_text='Enter End Year (e.g. 2022)'),
        ),
        migrations.AlterField(
            model_name='workmodels',
            name='start_from',
            field=models.IntegerField(help_text='Enter Start Year (e.g. 2020)'),
        ),
    ]
