# Generated by Django 5.2.8 on 2025-12-10 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0008_alter_workmodels_end_at_alter_workmodels_start_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodels',
            name='value',
            field=models.BigIntegerField(verbose_name='Value (₹)'),
        ),
    ]
