# Generated by Django 5.2.8 on 2025-12-10 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('datafeed', '0009_alter_workmodels_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workmodels',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
