# Generated by Django 5.1.4 on 2025-12-02 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('mobile_no', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('district', models.CharField(max_length=100)),
                ('massage', models.TextField(max_length=400)),
            ],
        ),
    ]
